name: CI

on:
  push:
    branches: [main]

jobs:
  library_tests:
    name: Library tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'
      - name: Build
        run: go build -v ./src/...
      - name: Test
        run: go test -v ./src/...
  library_template_tests:
    name: Library template tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'
      - name: Build
        run: go build -v ./...
      - name: Generate leetcode library template
        run: go run tools/leetcode_library_template_builder/main.go
      - name: Run leetcode library template tests
        run: go run tools/leetcode_library_template_tester/main.go || exit 1
  library_template_staleness_check:
    name: Check generated files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'
      - name: Build
        run: go build -v ./...
      - name: Generate leetcode library template
        run: go run tools/leetcode_library_template_builder/main.go
      - name: Check that generated files are unchanged
        run: git diff --exit-code HEAD || exit 1
