name: CI

on:
  push:
    branches: [main]

jobs:
  generated:
    name: Check generated files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'
      - name: Build
        run: go build -v ./...
      - name: Generate library
        run: go run build/build.go
      - name: Check that generated files are unchanged
        run: git diff --exit-code HEAD || exit 1
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
